### ISSUE TITLE
Pagination not working on page zoom out

### ISSUE THREAD

**Issue by Abhisheksth** [h920526/jQueryLazyScrollLoading#1]
The lazy scroll/pagination doesn't seem to be working when I click zoom out and refresh the page and try to scroll.

**Comment by h920526** [comment]
Thanks for your reply, but I can't reproduction this issue at Chrome 35 and IE 11.
Can you provide me more info?

ps. My demo page under dropbox doesn't work recently, because it change the protocol to HTTPS
