### ISSUE TITLE
fireOnScrollEvent not called if not scrolled to top-left corner

### ISSUE THREAD

**Issue by LeboyX** [h920526/jQueryLazyScrollLoading#2]
**Steps to Reproduce**
- Have an element in the page w/ multiple "lazy" items
- Scroll, trigger the load of the newly visible elements
- Empty the element w/ your "lazy" items, and append a new one w/ some lazy items in it
  - Note that your browser viewport should not be at the top of the page as this point
- Bind the lazyscrollloading widget to the new element

**Actual Results**
My "onLazyItemFirstVisible" callback isn't called until I manually scroll

**Expected Results**
My "onLazyItemFirstVisible" should be called on widget init.

**NOTE**: If I have time, I may fork and submit a pull request to fix this issue.

**Comment by h920526** [comment]
Which browser version do you use?

**Comment by LeboyX** [comment]
I was on Chrome at the time. Not sure what version it was on back then.

**Comment by h920526** [comment]
Could you try to init lazyscrollloading widget after you appending a new one?
It should solve your problem.

ps. or call refreshLazyScrollLoading()

**Comment by h920526** [comment]
or call refreshLazyScrollLoading
