### ISSUE TITLE
lazyscrollloading.js isn't working with chrome 47.0.2526.16 beta-m  (64-bit)

### ISSUE THREAD

**Issue by shadysherif** [h920526/jQueryLazyScrollLoading#4]
I don't know what is the problem but it isn't working, I tried to updated google chrome to 47.0.2526.27 beta-m (64-bit)

It doesn't work too.

people opened issues that google chrome it self has a bug in scrolling
https://code.google.com/p/chromium/issues/detail?id=544460&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

could you check what is the problem, I have a lot of work based on your js lib.

thanks

**Comment by h920526** [comment]
I tried google chrome 47.0.2526.49 beta-m (64 bit) @Windows 7 64bit, and it works fine.
Do you still have this problem?
